### ISSUE TITLE
Create battery icons

### ISSUE THREAD

**Issue by supreethaPavank** [siemens/ix-icons#15]
## I'm submitting a...

<pre><code>
[ ] Bug report
[ x] Feature request 
[ ] Documentation issue or request
</code></pre>

## Current behavior
No icons to represent battery health which is critical for IoT aPPS

## Expected behavior

Someway show low battery, recharged batery, time to change

## What is the motivation / use case for changing the behavior?

Need for IoT Apps

**Comment by silviowolf** [comment]
Hi @supreethaPavank, how many battery states should we provide?  
E.g. for the WLAN icon we provide 4 states:  
![image](https://user-images.githubusercontent.com/115155312/205006142-750c0d4b-7da6-4817-a785-9f8fa9d6bf61.png)
Aligned with that a set of battery icons would have the following states:
- battery-0 (empty battery with "!")
- battery-1 (almost empty battey, only a thin bar at the left)
- battery-2 (half filled battery)
- battery-3 (filled battery)

Would these states be sufficient for your usecase?

**Comment by silviowolf** [comment]
@supreethaPavank , first proposal:  
![image](https://user-images.githubusercontent.com/115155312/205012425-a1ba5a34-4a60-45d9-9c31-e1647e3e3b31.png)

**Comment by supreethaPavank** [comment]
Hi Silvio,

I want to know when battery is below 25%
When battery is 0
When battery has lost connection or signal
Battery > 25%

**Comment by silviowolf** [comment]
Icons are added and will be available with next build.

**Comment by silviowolf** [comment]
Issue can be closed.
