### ISSUE TITLE
Icon Request: Add new Tag

### ISSUE THREAD

**Issue by supreethaPavank** [siemens/ix-icons#22]
## I'm submitting a...

<pre><code>
[ ] Bug report
[ x] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

 None

## Expected behavior

Add a tag with plus icon which tells user that they can add new tags.
https://thenounproject.com/icon/add-tag-147065/

**Comment by silviowolf** [comment]
Agreed, will be integrated with next release.

**Comment by silviowolf** [comment]
https://agileworld.siemens.cloud/jira/browse/IX-90

**Comment by silviowolf** [comment]
Will be done with #20

**Comment by silviowolf** [comment]
@issue can be closed, I cannot do this.
