### ISSUE TITLE
Icon request: Documentation / Learn

### ISSUE THREAD

**Issue by susafors** [siemens/ix-icons#32]
## I'm submitting an icon request

<pre><code>
[ ] Bug report
[x ] Feature request
[ ] Documentation issue or request
</code></pre>

## Use case

We need an icon that tells the user where to find the documentation or learning content.

## Expected behavior
Preferred design: 
![image](https://github.com/siemens/ix-icons/assets/5981400/03dc9dfa-c155-4615-81ca-b4e93ffc4b68)
https://mui.com/material-ui/material-icons/?query=localli

**Comment by silviowolf** [comment]
Added to internal backlog

**Comment by silviowolf** [comment]
will be added with next release.
Name (regarding pictured objects)
user-reading(-filled)

**Comment by nuke-ellington** [comment]
Icon is now available
