### ISSUE TITLE
Icon request: Workspace

### ISSUE THREAD

**Issue by susafors** [siemens/ix-icons#35]
## I'm submitting a icon request
... for a workspace manager. Workspace is a virtual working environment in the cloud that can be accessed via the browser.

<pre><code>
[ ] Bug report
[ x] Feature request
[ ] Documentation issue or request
</code></pre>

## Expected behavior

![image](https://github.com/siemens/ix-icons/assets/5981400/d45cd0fb-8ffd-4536-a1b3-e6f652ed7470)

**Comment by silviowolf** [comment]
Added to internal backlog

**Comment by silviowolf** [comment]
Will be added with next release.
Names:
- worksapce
- workspaces

**Comment by nuke-ellington** [comment]
Icons are now available
