### ISSUE TITLE
Icon Request: Disabled camera

### ISSUE THREAD

**Issue by dorareviczki** [siemens/ix-icons#36]
[ ] Bug report
[x ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

None

## Expected behavior

I would like to order a disabled version of the camera icon. The application which we develop handles cameras and we need an icon which represents the disabled state of the camera.
Something similar like this one, but of course in an IX environment.
https://www.iconfinder.com/icons/4926490/camera_disable_disallow_no_photography_icon

**Comment by silviowolf** [comment]
OK, will be added with next release.
Name:
- photo-camera-cancelled(-filled)

Related icons will also be added:
- surveillance-cancelled(-filled)
- webcam-cancelled(-filled)

**Comment by dorareviczki** [comment]
Thank you, and also for the quick answer! When will the new release takes place?

**Comment by nuke-ellington** [comment]
Icons are now available
