### ISSUE TITLE
ix-icon does not support title 

### ISSUE THREAD

**Issue by supreethaPavank** [siemens/ix-icons#43]
## I'm submitting a...

<pre><code>
[ ] Bug report
[x] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior
<ix-icon name="star" size="16"></ix-icon>
does not support title. 

## Expected behavior

On hover, we want to show additional information on a tooltip

## Minimal reproduction of the problem with instructions
This was previously supported as title in core UI

**Comment by nuke-ellington** [comment]
This should get fixed via #48
