### ISSUE TITLE
Disable tooltip on hover

### ISSUE THREAD

**Issue by mahmoud-hosny92** [siemens/ix-icons#48]
## I'm submitting a...

<pre><code>
[ x ] Bug report
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

The icon name appears in a tooltip when it's on hover. If I've a custom tooltip on the icon, then two tooltips will appear.

## Expected behavior

Disable the icon name tooltip

## Minimal reproduction of the problem with instructions
We are using icons with the following components:

1. icon inside ix-event-list-item
2. ix-icon-button
3. ix-button with icon
4. ix-dropdown-button
5. icon inside ix-input-group
6. ix-dropdown-item with icon

## What is the motivation / use case for changing the behavior?

I believe it's a bug.

**Comment by nuke-ellington** [comment]
We will remove title tags from all SVGs @silviowolf

**Comment by nuke-ellington** [comment]
Closes siemens/ix#903

**Comment by silviowolf** [comment]
title attributes removed, pull requested https://github.com/siemens/ix-icons/pull/49
