### ISSUE TITLE
React: Visibility Issue with IX Icons on Production Build

### ISSUE THREAD

**Issue by rkoszo** [siemens/ix-icons#55]
## I'm submitting a...

<pre><code>
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior
We've recently transitioned to IX, but we've encountered a problem. Unfortunately, we are facing a challenge as the IX icons are not visible on our production build.
Interestingly, during my investigation, I found that Font Awesome and MUI icons are displaying correctly. I have been experimenting with various approaches to resolve this issue, but the IX icons remain the same.

Here are the environment details for your reference:
•             Operating System: Debian
•             Node Versions: 18.16.0 / 20.10.0 / 20.11.0
•             React Version: 18.2.0
•             @siemens/ix-icons Versions: 2.0.0 / 2.1.0
•             @siemens/ix-react Version: 2.0.4
•             Bundler: Rollup / SWC

Thank you in advance.

**Comment by danielleroux** [comment]
Please create the issue in the correct repository https://github.com/siemens/ix
