### ISSUE TITLE
Addition of SD Card icon(s)

### ISSUE THREAD

**Issue by preston-cunningham** [siemens/ix-icons#57]
## I'm submitting a...

<pre><code>
[ ] Bug report
[X] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

There are currently no SD card icons. There are some that are close but don't match exactly to a physical SD card.

## Expected behavior

A solid-fill and outline version of an SD card icon.

## What is the motivation / use case for changing the behavior?

We are building an interface that has SD card interactions and we would like an icon to reflect the intention of this tab.

**Comment by silviowolf** [comment]
@preston-cunningham, we will add a SD card icon (outline + filled) with a next update. I will attach the SVG files here as soon as we have created it. So you don’t have to wait for the release.

**Comment by silviowolf** [comment]
Hi @preston-cunningham, these SD Card icons are coming with next icon update. Find attached the SVGs in advance.
![sd-card-micro-filled](https://github.com/siemens/ix-icons/assets/115155312/432d94df-a63a-44df-a5b8-09bb8c29b3ea)
![sd-card-micro](https://github.com/siemens/ix-icons/assets/115155312/5661f1e3-de22-43c1-bb85-dcccb2f2ed56)
![sd-card-filled](https://github.com/siemens/ix-icons/assets/115155312/494baf7c-9a40-4283-aff1-541dd49fe842)
![sd-card](https://github.com/siemens/ix-icons/assets/115155312/064aeb9f-8390-4dbf-9078-fe143334130d)
