### ISSUE TITLE
Cannot find module '@stencil/core/internal/client'

### ISSUE THREAD

**Issue by cerenbattal** [siemens/ix-icons#60]
## I'm submitting a...

<pre><code>
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

We are having issues with our Jest unit tests on a React project. When we run tests, we get the following error on all our unit tests:

![image](https://github.com/siemens/ix-icons/assets/32881697/d3c58670-b70a-475e-89e2-47e7105b6427)

A new release on ```@stencil``` to solve this problem is available, and we found out that ix and ix-react also have a new release 2.4.0. We installed 2.4.0 but unfortunately, we get the same error again on our Jest unit tests.
On UI builds, we do not have this problem. 

## Expected behavior

Pass the tests without the error.

## Minimal reproduction of the problem with instructions
Here is our package.json:
```
  "devDependencies": {
    "@babel/cli": "^7.19.3",
    "@babel/core": "^7.19.3",
    "@babel/plugin-transform-private-methods": "^7.23.3",
    "@babel/preset-env": "^7.19.4",
    "@babel/preset-react": "^7.18.6",
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^12.8.3",

    .....

    "jest": "^29.2.1",
    "jest-environment-jsdom": "^29.3.1",
    
    ....

  },
  "dependencies": {
    ....
    "@siemens/ix": "^2.4.0",
    "@siemens/ix-brand-theme": "^2.0.0",
    "@siemens/ix-echarts": "^2.1.1",
    "@siemens/ix-icons": "^2.2.0",
    "@siemens/ix-react": "^2.4.0",
    ....
  },
  ```

## What is the motivation / use case for changing the behavior?

We need to get the project-specific icons for our product release. These icons have been merged on ix-icons 2.2.0.

**Comment by danielleroux** [comment]
Please provide accessible code (no private repositories) to reproduce the problem (preferred github repository, stackblitz or codesandbox).

**Comment by cerenbattal** [comment]
Hi,

I solved the problem by removing the node_modules and package-lock.json, running 'npm install' again. Thank you for your support.
