### ISSUE TITLE
New icon to be added in ix-icons

### ISSUE THREAD

**Issue by sawantaarti** [siemens/ix-icons#63]
## I'm submitting a...

<pre><code>

[ ] Feature request

</code></pre>

## new icon request in ix-icons : SMO icons: https://smo-design-system.code.siemens.io/design-basics/ui-icons

icon name (train-m, train-s) --> mobility specific icons 

## What is the motivation / use case for changing the behavior?

#37

**Comment by silviowolf** [comment]
Hi @sawantaarti the icon train-m has already been added as "train-filled". the -s variant will not be added as default design-size in iX is 24x24.
